server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/customers/**

            - id: shopkeeper-service
              uri: lb://SHOPKEEPER-SERVICE
              predicates:
                - Path=/shopkeepers/**

            - id: item-service
              uri: lb://ITEM-SERVICE
              predicates:
                - Path=/items/**

            - id: transaction-service
              uri: lb://TRANSACTION-SERVICE
              predicates:
                - Path=/transactions/**

            - id: ledger-service
              uri: lb://LEDGER-SERVICE
              predicates:
                - Path=/ledgers/**

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true